### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by mdoallo** [utn-ba-rf-lab/gr-serializer#4]
Hay que remover este control, así puedo probar otras velocidades.
Quiero evaluar 96 KSamp/Sg y 128 KSamp/Sg.
Sí hay que esperar el "OK" de la placa comenzar.

![Screenshot_20240701_190044](https://github.com/utn-ba-rf-lab/gr-serializer/assets/62174402/cddcb47f-d912-4f5a-bd5b-6476b9eec8e6)

**Comment by leandrobottinelli** [comment]
Quedo creada una nueva branch [unlimited_sample_rate](https://github.com/utn-ba-rf-lab/gr-serializer/tree/unlimited_sample_rate) para que se pueda hacer pruebas sin limitacion en el valor de sample rate elegido.

**Comment by mdoallo** [comment]
Anda muy bien Leandro, gracias. A continuación la salida que tengo en consola cuando uso una velocidad no soportada por el hardware:

```
Executing: /usr/bin/python3 -u /usr/local/src/gr-serializer/examples/test_serial.py

Warning: failed to XInitThreads()
[INFO] | Path: /dev/ttyUSB1
[INFO] | Mode: data
[INFO] | Sample rate: 49000
[RX] | Detecting board..
[DEBUG] | RX: UTNv2

[INFO] | Board detected: Mercurial X kHz
[ERROR] | RX: ERROR

[ERROR] | No board detected

>>> Done
```

**Comment by mdoallo** [comment]
Te contesté por GitHub pero también lo hago por acá.
Funcionó muy bien Gracias.
Cuando puedas hace el merge de esta rama y vamos a por la limitación en
amplitud.
Abrazo.
